DROP TABLE IF EXISTS `qfy_andon_repair_mo`;
CREATE TABLE `qfy_andon_repair_mo`
(
    id varchar(36) NOT NULL COMMENT '主键' PRIMARY KEY,
    sys_org_code    varchar(50)              NULL COMMENT '所属部门',
    remarks         varchar(300)             NULL COMMENT '备注',
    catalog         varchar(10)              NULL COMMENT '目标类型',
    src_doc_type    varchar(50) CHARSET utf8 NULL COMMENT '来源单据类别',
    src_doc_code    varchar(36)              NULL COMMENT '来源单据编号',
    mo_code         varchar(36)              NOT NULL COMMENT '维修单号',
    deviceno        varchar(36)              NULL COMMENT '设备单号',
    dev_name        varchar(100)             NULL COMMENT '设备名称',
    wc_name         varchar(30) CHARSET utf8 NULL COMMENT '工作中心名称',
    wc_code         varchar(30) CHARSET utf8 NULL COMMENT '工作中心',
    location        varchar(100)             NULL COMMENT '设备存放位置',
    rec_date        varchar(20)              NULL COMMENT '发生时间',
    notifier        varchar(20)              NULL COMMENT '报障人',
    notifier_name   varchar(50)              NULL COMMENT '报障人',
    notifier_phone  varchar(50)              NULL COMMENT '报障人电话',
    notice_depart   varchar(36)              NULL COMMENT '报障部门',
    abnormal_level  varchar(36)              NULL COMMENT '故障等级',
    abnormal_name   varchar(60)              NULL COMMENT '故障类型名称',
    abnormal_code   varchar(36)              NULL COMMENT '故障类型',
    happen_pos      varchar(50)              NULL COMMENT '故障部位',
    fault_code      varchar(36)              NULL COMMENT '故障原因',
    duty_depart     varchar(36)              NULL COMMENT '维修组 责任部门',
    duty_man        varchar(36)              NULL COMMENT '维修人 责任人',
    duty_man_id     varchar(50)              NULL COMMENT '维修人',
    critical_level  varchar(36)              NULL COMMENT '紧急程度 紧急、高、中、低',
    be_stop         varchar(2)               NULL COMMENT '是否停机',
    abn_content     varchar(200)             NULL COMMENT '故障描述',
    resolution_time varchar(20)              NULL COMMENT '要求截止时间',
    abn_files       varchar(1000)            NULL COMMENT '关联附件列表',
    shenp_man       varchar(36)              NULL COMMENT '审批用户',
    shenp_man_id    varchar(50)              NULL COMMENT '审批用户',
    shenpjz_time    varchar(20)              NULL COMMENT '审批截止时间',
    shenp_time      varchar(20)              NULL COMMENT '审批时间',
    shenp_result    varchar(20)              NULL COMMENT '审批结果',
    shenp_content   varchar(200)             NULL COMMENT '审批内容',
    weix_state      varchar(36)              NULL COMMENT '维修状态',
    weix_level      varchar(36)              NULL COMMENT '维修级别',
    weix_type       varchar(36)              NULL COMMENT '维修类别',
    weix_stdate     varchar(20)              NULL COMMENT '维修开始时间',
    weix_eddate     varchar(20)              NULL COMMENT '维修完成时间',
    weix_times      int(8)                   NULL COMMENT '维修时长(分钟) 完成时间-开始时间',
    stop_times      int(8)                   NULL COMMENT '停机时长(分钟)',
    weix_amount     double(10, 2)            NULL COMMENT '维修费用',
    weix_files      varchar(255)             NULL COMMENT '维修执行关联附件列表',
    baox_item_limit int(5)                   NULL COMMENT '保修期限',
    weix_content    varchar(1000)            NULL COMMENT '维修工作描述',
    mo_state        int(3)                   NULL COMMENT '工单状态',
    is_outs         int(1) DEFAULT 0         NULL COMMENT '是否委外',
    outs_name       varchar(50)              NULL COMMENT '委外企业',
    outs_id         varchar(50)              NULL COMMENT '委外企业id',
    outs_tel        varchar(20)              NULL COMMENT '委外企业名称',
    is_finish       int(2)                   NULL COMMENT '工单是否完结',
    shif_amount     double(8, 2)             NULL COMMENT '实付费用',
    parts_fee       double(8, 2)             NULL COMMENT '零件费用',
    assist_fee      double(8, 2)             NULL COMMENT '外协费用',
    other_fee       double(8, 2)             NULL COMMENT '其他费用',
    s1              varchar(50)              NULL COMMENT 's1',
    s2              varchar(50)              NULL COMMENT 's2',
    s3              varchar(50)              NULL COMMENT 's3',
    s4              varchar(50)              NULL COMMENT 's4',
    s5              varchar(50)              NULL COMMENT 's5',
    i1              int(10)                  NULL COMMENT 'i1',
    i2              int(10)                  NULL COMMENT 'i2',
    i3              int(10)                  NULL COMMENT 'i3',
    d1              double(4, 1)             NULL COMMENT 'd1',
    d2              double(4, 1)             NULL COMMENT 'd2',
    d3              double(4, 1)             NULL COMMENT 'd3',
    create_by       varchar(32)              NULL COMMENT '创建人',
    create_time     datetime                 NULL COMMENT '创建时间',
    update_by       varchar(32)              NULL COMMENT '修改人',
    update_time     datetime                 NULL COMMENT '修改时间',
    del_flag        varchar(1)               NULL COMMENT '0表示未删除,1表示删除',
    sign_man_id     varchar(32) CHARSET utf8 NULL COMMENT '签到人',
    sign_man        varchar(50) CHARSET utf8 NULL COMMENT '签到人姓名',
    sign_time       varchar(20)              NULL COMMENT '响应截止时间'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic COMMENT '维修工单表';

CREATE INDEX `doc_code` ON `qfy_andon_repair_mo` (`src_doc_code`);
CREATE INDEX `mo_code` ON `qfy_andon_repair_mo` (`mo_code`);

CREATE TABLE `qfy_andon_repair_mo_log`
(
    id varchar(36)   NOT NULL COMMENT '主键' PRIMARY KEY,
    mo_code       varchar(36)   NULL COMMENT '维修单号',
    opt_id        varchar(20)   NULL COMMENT '操作人',
    opt_name      varchar(200)  NULL COMMENT '操作人',
    opt_content   varchar(1000) NULL COMMENT '日志内容',
    opt_type      varchar(36)   NULL COMMENT '日志类型',
    opt_data_json text          NULL COMMENT '参数',
    result_msg    varchar(50)   NULL COMMENT 'resultMsg',
    s1            varchar(50)   NULL COMMENT '扩展字段1',
    s2            varchar(255)  NULL COMMENT '扩展字段2',
    s3            varchar(50)   NULL COMMENT '扩展字段3',
    s4            varchar(50)   NULL COMMENT '扩展字段4',
    create_by     varchar(32)   NULL COMMENT '创建人',
    create_time   datetime      NULL COMMENT '创建时间',
    update_by     varchar(32)   NULL COMMENT '修改人',
    update_time   datetime      NULL COMMENT '修改时间',
    del_flag      varchar(1)    NULL COMMENT '0表示未删除,1表示删除',
    sys_org_code  varchar(50)   NULL COMMENT '所属部门',
    remarks       varchar(255)  NULL COMMENT 'remarks'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic COMMENT '维修工单日志';

CREATE INDEX `mo_code` ON `qfy_andon_repair_mo_log` (`mo_code`);

ALTER TABLE sys_user ADD COLUMN district_code varchar(32) NULL COMMENT '管辖行政区划编码';

INSERT INTO flyway_schema_history VALUES (null,'1.24.0120','upgrade','SQL','V1_24_0120__upgrade.sql',0,'root',now(),1,1);
